name = "Jacobi-Experiments"
version = "0.1.0"
license = "license"
maintainer = "jane.doe@example.com"
author = "Jane Doe"
copyright = "Copyright 2020 Jane Doe"

[install] # Options for the "install" subcommand
library = false

[build] # General Build Options
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[dependencies]
stdlib = "*"
openmp = "*"
spacefill = {git="https://github.com/program--/spacefill.git"}

[dev-dependencies]

[[test]]
name="runTests"
source-dir="test"
main="check.f90"


[[example]]
name="demo"
source-dir="example"
main="demo.f90"
