name = "JacobiExperiments"
uuid = "d7403ced-9bae-48ac-8b71-fed939355880"
authors = ["Jane Doe <jane.doe@example.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DelimitedFiles = "1.9.1"
LinearAlgebra = "1.11.0"
